apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager-test
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: test-selfsigned
  namespace: cert-manager-test
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: development@two2.jp
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}

    dns01:
      providers:
      - name: prod-dns
        clouddns:
          serviceAccountSecretRef:
            name: clouddns-service-account
            key: cert-manager-key.json
          # The project in which to update the DNS zone
          project: testing-20190417

---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: selfsigned-cert
  namespace: cert-manager-test
spec:
  commonName: ssl-sleepdays.com
  secretName: selfsigned-cert-tls
  issuerRef:
    name: test-selfsigned
  dnsNames:
  - ssl-sleepdays.com
  acme:
    config:
    - dns01:
        provider: prod-dns
      domains:
      - ssl-sleepdays.com
