apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    # kubernetes.io/ingress.class: "nginx"
    # kubernetes.io/tls-acme: 'true'
    # certmanager.k8s.io/issuer: "letsencrypt-staging"
    # certmanager.k8s.io/acme-challenge-type: http01
spec:
  rules:
  - host: development.barth.jp
    http:
      paths:
      - path: /*
        backend:
          serviceName: webserver-service
          servicePort: 3000
  # tls:
  #   - hosts:
  #       - "ssl-testing.work"
  #     secretName: letsencrypt-staging
