default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  #username: <%= ENV['MYSQL_USER'] %>
  #password: <%= ENV['MYSQL_PASSWORD'] %>
  username: <%= ENV['MYSQL_USER'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  host: <%= ENV.fetch("DB_HOST") { '192.168.33.10' }  %>

development:
  <<: *default
  database: sleepdays_development

test:
  <<: *default
  database: sleepdays_test

production:
  <<: *default
  database: sleepdays_production

