default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['MYSQL_USER'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  host: <%= ENV.fetch("DB_HOST") { '192.168.33.1' }  %>

development:
  <<: *default
  database: sample_docker_development


test:
  <<: *default
  database: sample_docker_test

production:
  <<: *default
  database: sample_docker_production
