apiVersion: v1
kind: ConfigMap
metadata:
  name: rails-config
data:
  RAILS_ENV: 'development'
  MYSQL_HOST: 'mysql'
  MYSQL_USER: 'root'
  MYSQL_ROOT_PASSWORD: 'root'
  DB_HOST: 'dbserver-service.default.svc.cluster.local'
