apiVersion: batch/v1
kind: Job
metadata:
  name: rails-setup
spec:
  template:
    metadata:
      name: rails-setup
    spec:
      containers:
      - name: rails-setup
        image: asia.gcr.io/testing-20190417/sample_docker/app:latest
        #alwaysだとNG　imagePullSecretsで設定しないとだめかも
        imagePullPolicy: Never
        command: ["/bin/sh"]
        args: ["-c", "bundle exec rails db:create && bundle exec rails db:migrate"]
        envFrom:
        - configMapRef:
            name: rails-config
      restartPolicy: Never
