apiVersion: batch/v1
kind: Job
metadata:
  name: rails-setup
spec:
  template:
    metadata:
      name: rails-setup
    spec:
      containers:
      - name: rails-setup
        image: keiichihonma/sample_docker_app:latest
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "bundle exec rails db:create && bundle exec rails db:migrate"]
        envFrom:
        - configMapRef:
            name: rails-config
      restartPolicy: Never
