apiVersion: v1
data:
  password: CoWxa7cDQx5yDisN848VOzaznOGdVLnL6XQ61mkpwL3Ain6IK6OW+m5Zlc4OeoPr.SZy0KxuxThxuT9/l.ndxcfjT+xn7jVUYI15IPVg==
  rootname: LaG0998ZJP4T/zuY+rc7lAPaN5Uz1FYSvrc17EJglHASNrjVc2srjon5Z9+WBPpZ.Y88VQihCneSNJqxN.FayP78hEtNEPOuUXqgPl2Q==
  rootpass: m5ncWYng6it39rU37dFLzIaLQ2GlfMFb4vMIERc9MGfEyuzhDPY2g56oFBz6qCRU.F+vSTPzPmyTNMhW1.+AmUuwmYzEdla0Yl6vZZtQ==
  secret_key_base: CSy5zLXvkS3pUCrUXjoNaulN/6fScRpvq1bPUfS04xII74fQyx9VrjzgxgWFM50b.usoccIZqowzZfjGj.lKzgUngYRGgclHfy/neI8w==
  username: zRvWdTo1ftFxLT8wFuv2Am+CLpDaIgef0x2dMlA9C7cXHPwnTZ6pJKEAXsXss6dV.tuHPCQ6qXqPUP10w.A57DUZkPPKN+tl8RsgC+Qw==
kind: Secret
metadata:
  name: secret
type: Opaque
# kubesec:v:3
# kubesec:gcp:projects/testing-20190417/locations/global/keyRings/two/cryptoKeys/sleepdays:CiQAg263K70zBFVeDnQslVujBi89vEsjd9UyE9OLAEHB1JtwzxESSQBkiOELTuSz43QCnKFZf/5POdnzio8hoU28eSkDV8R7BoorkMFchmd9TV/JzQWLIZASRdBSf73DiGB8WBN++6YhFagDzzW4Euo=
# kubesec:mac:lmrJU7s3iekcZKZj.CR5hmhmT6qLcFZaajI3hyw==
